import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Hero } from "@/components/Hero";

const j = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hokkah Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${j.className} antialiased`}>
        <Header />
        <Hero />
        {children}
      </body>
    </html>
  );
}
